# NumPy Pre-Class Exercises 

We've learned about NumPy and Numpy built-in methos. Let's test your knowledge. (Refer to the pre-class video for the answers)

Import Numpy

In [2]:
import numpy as np

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [8]:
my_list = [1,2,3,4]
my_list

[1, 2, 3, 4]

In [11]:
np.array(my_list)

array([1, 2, 3, 4])

In [12]:
my_matrix = [[1,2,3,4], [5,6,7,8], [9, 10, 11, 12]]
my_matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [14]:
np.array(my_matrix)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [15]:
np. arange(0, 15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
np.arange(0,13,3)

array([ 0,  3,  6,  9, 12])

### zeros and ones

Generate arrays of zeros or ones

In [17]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [20]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [54]:
np.linspace(0,10,4)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [55]:
np.linspace(0,5,25)

array([0.        , 0.20833333, 0.41666667, 0.625     , 0.83333333,
       1.04166667, 1.25      , 1.45833333, 1.66666667, 1.875     ,
       2.08333333, 2.29166667, 2.5       , 2.70833333, 2.91666667,
       3.125     , 3.33333333, 3.54166667, 3.75      , 3.95833333,
       4.16666667, 4.375     , 4.58333333, 4.79166667, 5.        ])

## eye

Creates an identity matrix

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [25]:
np.random.rand(5)

array([0.90082536, 0.73517894, 0.62119371, 0.96446247, 0.44342191])

In [26]:
np.random.rand(4,4)

array([[0.70360417, 0.90684827, 0.81062054, 0.23754771],
       [0.45417212, 0.84729274, 0.33778327, 0.70433936],
       [0.19955382, 0.46789504, 0.11552843, 0.9392155 ],
       [0.31478353, 0.27464444, 0.65122131, 0.14951494]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [27]:
np.random.randn(3)

array([-1.56903552, -0.93821559,  0.29166866])

In [28]:
np.random.randn(4,4)

array([[-0.49511804, -1.41054107,  2.33642593,  0.17748805],
       [ 1.09284341, -1.36337353,  0.99105937,  0.11781786],
       [-0.27727538,  0.54797149, -0.12457605, -0.49214647],
       [ 0.99700289,  0.42727487, -0.17934676,  1.30881311]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [32]:
np.random.randint(100)

3

In [33]:
np.random.randint(1,50,10)

array([12, 33,  5, 29, 30,  9, 33,  3, 35, 29])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [4]:
arr = np.arange(25)
ranarr = np.random.randint(0, 50, 10)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [6]:
ranarr

array([34, 16, 13, 24, 16,  2, 30, 39, 40, 40])

## Reshape
Returns an array containing the same data with a new shape.

In [7]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [8]:
ranarr

array([34, 16, 13, 24, 16,  2, 30, 39, 40, 40])

In [9]:
ranarr.max()

40

In [10]:
ranarr.argmax()

8

In [11]:
ranarr.min()

2

In [12]:
ranarr.argmin()

5

## Shape

Shape is an attribute that arrays have (not a method):

In [13]:
arr.shape

(25,)

In [14]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [15]:
arr.reshape(1, 25).shape

(1, 25)

In [16]:
arr.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [49]:
arr.reshape(25, 1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [50]:
arr.dtype

dtype('int64')

# Great Job!